version: '2'

services:
  
  base:
    build: .
    image: developmentseed/cumulus:base
    entrypoint: /bin/bash
    env_file: .env
    volumes:
      - '.:/home/cumulus/work'

  test:
    image: developmentseed/cumulus:base
    entrypoint: bash -c 'nosetests -v -s --with-coverage --cover-package cumulus --cover-inclusive --with-timer -v -s;'
    env_file: .env
    volumes:
      - './test:/home/cumulus/work'
