version: '2'

services:
  
  build:
    build: .
    image: cumulus:base

  bash:
    image: cumulus:base
    entrypoint: /bin/bash

  test:
    image: cumulus:base
    entrypoint: bash -c 'nosetests --with-coverage --cover-package modispds --cover-inclusive --with-timer -v -s;'
    working_dir: /work
    volumes:
      - '.:/work'