# Python CircleCI 2.0 configuration file
version: 2

references:
  container_python27: &container_python27
    docker:
      - image: circleci/python:2.7.13
    working_dir: ~/project

  container_python36: &container_python36
    docker:
      - image: circleci/python:3.6.2
    working_dir: ~/project

  restore_repo: &restore_repo
    restore_cache:
      keys:
        - v0-repo-{{ .Branch }}-{{ .Revision }}
        - v0-repo-{{ .Branch }}
        - v0-repo

  save_repo: &save_repo
    save_cache:
      key: v0-repo-{{ .Branch }}-{{ .Revision }}
      paths:
        - ~/project  

  restore_dependencies27: &restore_dependencies27
    restore_cache:
      keys:
        - v0-dependencies27-{{ checksum "requirements.txt" }}
        - v0-dependencies27

  restore_dependencies36: &restore_dependencies36
    restore_cache:
      keys:
        - v0-dependencies36-{{ checksum "requirements.txt" }}
        - v0-dependencies36

jobs:

  checkout_code:
    <<: *container_python36
    steps:
      - *restore_repo
      - checkout
      - *save_repo

  install_and_test_27:
    <<: *container_python27
    steps:  
      - *restore_repo
      - *restore_dependencies27
      - run:
          name: Install virtualenv
          command: pip install virtualenv
      - run: 
          name: Install dependencies
          command: |
            virtualenv ~/venv27
            . ~/venv27/bin/activate
            pip install -r requirements.txt
            pip install -r requirements-dev.txt
      - save_cache:
          key: v0-dependencies27-{{ checksum "requirements.txt"}}
          paths:
            - ~/venv27
      - run :
          name: Run tests
          command: |
            . ~/venv27/bin/activate
            nosetests -v --with-coverage --cover-package cumulus

  install_and_test_36:
    <<: *container_python36
    steps:  
      - *restore_repo
      - *restore_dependencies36
      - run:
          name: Install virtualenv
          command: pip install --user virtualenv
      - run: 
          name: Install dependencies
          command: |
            ~/.local/bin/virtualenv ~/venv36
            . ~/venv36/bin/activate
            pip install -r requirements.txt
            pip install -r requirements-dev.txt
            nosetests -v --with-coverage --cover-package cumulus
      - save_cache:
          key: v0-dependencies36-{{ checksum "requirements.txt"}}
          paths:
            - ~/venv36
      - run :
          name: Run tests
          command: |
            . ~/venv36/bin/activate
            nosetests -v --with-coverage --cover-package cumulus

  deploy:
    <<: *container_python36
    steps:
      - *restore_repo
      - *restore_dependencies36
      - add_ssh_keys
      - run:
          name: Push tag to github
          command: |
            mkdir -p ~/.ssh
            ssh-keyscan github.com >> ~/.ssh/known_hosts
            VERSION=`awk -F\' '{print $2,$4}' cumulus/version.py`
            git tag $VERSION
            git push origin $VERSION
      - run:
          name: Deploy to PyPi
          command: |
            . ~/venv/bin/activate
            pip install twine
            python setup.py sdist
            twine upload --username "${PYPI_USER}" --password "${PYPI_PASS}" dist/*


workflows:
  version: 2
  build_test_36_deploy:
    jobs:
      - checkout_code
      - install_and_test_36:
          requires:
            - checkout_code
      - deploy:
          requires:
            - install_and_test_36
          filters:
            branches:
              only: master
  build_test_27:
    jobs:
      - checkout_code
      - install_and_test_27:
          requires:
            - checkout_code